### ISSUE TITLE
"Callback must be a function" error with 1.14

### ISSUE THREAD

**Issue by timmyRS** [PrismarineJS/minecraft-jar-extractor#6]
```
$ node downloadDecompile.js 1.14 /tmp/the_output
Decompiled at /tmp/the_output/decompiled
$ node protocol_extractor.js /tmp/the_output/decompiled
fs.js:133
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1179:14)
    at write (/root/minecraft-jar-extractor/protocol_extractor.js:29:6)
    at linesToProtocol (/root/minecraft-jar-extractor/protocol_extractor.js:49:3)
    at fn (/root/minecraft-jar-extractor/node_modules/async/lib/async.js:638:34)
    at Immediate.<anonymous> (/root/minecraft-jar-extractor/node_modules/async/lib/async.js:554:34)
    at processImmediate (internal/timers.js:443:21)
```

**Comment by rom1504** [comment]
fixed
