### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined (on 1.15 version)

### ISSUE THREAD

**Issue by uncovery** [PrismarineJS/minecraft-jar-extractor#7]
```
/image_name.js:249
  const itemTextures = mcData.itemsArray.map(item => {
                                        ^

TypeError: Cannot read property 'map' of undefined
    at getItems (/home/minecraft/server/mc_assets/assets-extract/image_name.js:249:41)
    at /home/minecraft/server/mc_assets/assets-extract/image_name.js:302:5
    at /home/minecraft/server/mc_assets/assets-extract/get_minecraft_files.js:19:7
    at ZipFile.<anonymous> (/home/minecraft/server/mc_assets/assets-extract/node_modules/extract-zip/index.js:40:11)
    at emitNone (events.js:86:13)
    at ZipFile.emit (events.js:185:7)
    at FdSlicer.<anonymous> (/home/minecraft/server/mc_assets/assets-extract/node_modules/yauzl/index.js:182:10)
    at FdSlicer.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at FdSlicer.emit (events.js:185:7)
    at onCloseDone (/home/minecraft/server/mc_assets/assets-extract/node_modules/fd-slicer/index.js:74:12)
    at /home/minecraft/server/mc_assets/assets-extract/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by uncovery** [comment]
any update regarding this? Thanks!!

**Comment by rom1504** [comment]
What command did you run exactly ?

**Comment by uncovery** [comment]
node image_names.js 1.15.2 out tmp

I think the issue might be that the 1.15.2 data does not exist (yet)?

**Comment by uncovery** [comment]
If I run this with 1.14, I get something else (but similar). Under what circumstances is this script supposed to work? Should it at least work for non-issue items and jump over the issues or is it desired behavior that it fails? I don't understand enough of the data structure to be able to say...

```
/minecraft-jar-extractor/image_names.js:250
    const model = itemMapping[item.name] ? itemMapping[item.name] : item.name
                             ^

TypeError: Cannot read property 'air' of undefined
    at mcData.itemsArray.map.item (/home/minecraft/server/mc_assets/minecraft-jar-extractor/image_names.js:250:30)
    at Array.map (<anonymous>)
    at getItems (/home/minecraft/server/mc_assets/minecraft-jar-extractor/image_names.js:249:42)
    at /home/minecraft/server/mc_assets/minecraft-jar-extractor/image_names.js:302:5
    at /home/minecraft/server/mc_assets/minecraft-jar-extractor/get_minecraft_files.js:19:7
    at ZipFile.<anonymous> (/home/minecraft/server/mc_assets/minecraft-jar-extractor/node_modules/extract-zip/index.js:46:11)
    at ZipFile.emit (events.js:198:13)
    at FdSlicer.<anonymous> (/home/minecraft/server/mc_assets/minecraft-jar-extractor/node_modules/yauzl/index.js:202:10)
    at Object.onceWrapper (events.js:286:20)
    at FdSlicer.emit (events.js:198:13)
    at onCloseDone (/home/minecraft/server/mc_assets/minecraft-jar-extractor/node_modules/fd-slicer/index.js:74:12)
    at /home/minecraft/server/mc_assets/minecraft-jar-extractor/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

**Comment by rom1504** [comment]
Didn't have time yet, but what I would do, and what you can do too is
looking at the code and making it work for recent versions.
As explained Mojang changes stuff every version, so these scripts often
need adapting.

**Comment by uncovery** [comment]
This seems to be fixed now, I am not sure what changed. It might be that now the relevant minecraft-data is available. 

I am sorry, but I am not able to debug this properly since I fail to understand the script and the underlying modules. 

IMHO In the end this issue is still open since the script does not alert about missing data nut simply fails.

**Comment by rom1504** [comment]
It's fixed yes
